### ISSUE TITLE
Ignore modifiers (alt, shift, ctrl) and always pass to host

### ISSUE THREAD

**Issue by lukaszsmoczynski** [neon-dev/RDPHotkeyHelper#10]
In my case I never want to control media on RDP, so it makes no sense to sense to not pass them do host.

Reason behind this is that I mapped `CTRL` + `VOLUME UP` as `NEXT TRACK`, but because modifiers block passing media button to host it will never work.
Also I'm not sure if that's intended, but `Shift` is not mentioned in readme, yet it also blocks the script.

**Comment by neon-dev** [comment]
Modifiers are not blocked, they are just not bound. The example in the readme is there just as a useful tip for some.

You can modify the `PassToLocalMachine` function using this example I gave in another issue:
https://github.com/neon-dev/RDPHotkeyHelper/issues/9#issuecomment-2108866125

Then add this line
```ahk
^Volume_Up::PassToLocalMachine("Media_Next")
```
above the modified function, so `CTRL` + `VOLUME UP` will switch to the next track.

**Comment by lukaszsmoczynski** [comment]
That makes sense. I'd suggest to add brief info about that in readme, but beside that I'm good.
