### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by biiiipy** [neon-dev/RDPHotkeyHelper#2]
Hi, looks like a great script!
Unfortunately, for me it doesn't work at all. Server and client are both Windows 10 21H2. Tried script and exe release.
Any ideas what could be the problem?

**Comment by neon-dev** [comment]
Hi, what language is your Windows where the script is running?

**Comment by biiiipy** [comment]
Yeah, on different languages remote desktop window will be called differently, so window identification will not work:
https://github.com/neon-dev/RDPHotkeyHelper/blob/e4db89d0e690712ed5e74966205625b52fa502bc/RDPHotkeyHelper.ahk#L14

Not sure if it's possible to WinWaitActive with ```ahk_class TscShellContainerClass```

As a workaround, one should edit the script to match their language

**Comment by neon-dev** [comment]
The title matches both RDP types of clients, the standard one and the Microsoft Store app. Store apps don't have unique classes unfortunately.
We could create a lookup function for better language support and implement the ahk_class as a fallback if the language is not supported, but it would add more complexity to the script and not support the store app with those languages. Not sure if it's worth it.

**Comment by biiiipy** [comment]
Yeah, definitely not worth the hassle, maybe just add a comment in the script / readme, that would be more than enough.

**Comment by neon-dev** [comment]
Addressed with 4138747
