### ISSUE TITLE
Media keys not working

### ISSUE THREAD

**Issue by ghost** [neon-dev/RDPHotkeyHelper#4]
Hi,

Thanks for your script! Volume keys are working nicely... :-)

However, somehow I can't seem to get the media keys to work. My RDP client is a Win10 machine.

Media keys work locally. 

Any ideas what might go wrong?

Thanks for your help.

**Comment by neon-dev** [comment]
Hi, are you sure your volume keys control the local volume when using this script? Which program(s) do you control with media keys?

**Comment by ghost** [comment]
> Hi, are you sure your volume keys control the local volume when using this script? Which program(s) do you control with media keys?

Yes, when I am in full screen mode on my RDP client the volume buttons work. I control for example VLC media player. There the global hotkeys Media_Play_Pause and Media_Next are configured. This works fine from my local machine, but from RDP client these don't work.

Somehow the media keys are not detected. I am running Windows Server 2016 on the remote client, can this be the problem?

**Comment by neon-dev** [comment]
It looks like VLC captures hotkeys differently than most other programs, so I don't know how this could be solved.
If you're playing media through your local web browser, media buttons should work. Please let me know if you find a workaround. Otherwise, as a last resort, you could try a different player.

**Comment by ghost** [comment]
I think you are right, I can confirm that spotify is working for example. Thanks again!
