### ISSUE TITLE
Port to v2

### ISSUE THREAD

**Issue by rolocampusano** [neon-dev/RDPHotkeyHelper#6]
Hi! I'm just starting to use ahk and realized that a bunch of the codes (like this one) are in v1. I can try porting this one to v2, but do you have any guidelines that I could follow? 

Thank you!

**Comment by neon-dev** [comment]
Hi, sure, feel free. I'm not overly familiar with AHK and haven't looked into v2 at all, so just follow official conventions and guidelines.
