### ISSUE TITLE
Hyper-V support

### ISSUE THREAD

**Issue by timtucker-dte** [neon-dev/RDPHotkeyHelper#7]
Would be good to add support for virtual machine connections via Hyper-V as well.

Should be relatively simple -- as best as I can tell the windows just end with the title " - Virtual Machine Connection"

Alternately, you could match based on executable: vmconnect.exe

**Comment by neon-dev** [comment]
New release published, let me know if there are any issues.
I could not test vmconnect.exe but since all process names are part of the same pattern, it should be fine (unless vmconnect.exe is not the actual window process).

**Comment by timtucker-dte** [comment]
Adding as an update:

This works.

In order to intercept keys from the Hyper-V window, though, AutoHotKey has to run the script with admin privileges.

Easiest way I found to do that was to add a scheduled task that launches the script using log on as a trigger.
