### ISSUE TITLE
Not recognizing play pause stop skip

### ISSUE THREAD

**Issue by Vikingscript** [neon-dev/RDPHotkeyHelper#8]
The hotkey script allows mute and volume button commands but play/pause, stop and skip are not working.

**Comment by neon-dev** [comment]
Hi, this sounds very similar to #4. Which players did you try?

**Comment by Vikingscript** [comment]
I've noticed this on Pandora

**Comment by neon-dev** [comment]
I don't have access to this in my country, but if play/pause works in your browser, for example, it means that Pandora has the same problem as VLC and that it's a limitation of the current implementation of the script.

**Comment by daetanbhuck** [comment]
MusicBee has this issue, as well (3.5.8).
